import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { HelpCircle, FileText } from 'lucide-react';

export function GapAnalysisGuide() {
  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="outline" size="sm" className="gap-1.5">
          <HelpCircle className="h-4 w-4" />
          Guide
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-3xl max-h-[85vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5 text-blue-600" />
            How to Read the Gap Analysis
          </DialogTitle>
        </DialogHeader>
        <div className="space-y-5 text-sm text-gray-700">
          <section>
            <h3 className="font-semibold text-gray-900 mb-1">What the gap analysis measures</h3>
            <p>
              For each appraisal section, the employee's self-rating is compared with the line manager's rating on a 1–5 scale. The target performance level is 4.0. Where the two views diverge significantly, the system flags a gap.
            </p>
          </section>

          <section>
            <h3 className="font-semibold text-gray-900 mb-1">Gap types</h3>
            <ul className="space-y-2 list-disc ml-5">
              <li>
                <strong>Performance Gap</strong> — the average of both ratings is below 3.5. This indicates the employee needs formal training or skill improvement in that area.
              </li>
              <li>
                <strong>Self-Assessment Gap (overconfidence)</strong> — the employee rates themselves more than 0.5 points higher than the manager. This suggests a calibration conversation with the line manager before any training is assigned.
              </li>
              <li>
                <strong>Confidence Gap (underconfidence)</strong> — the manager rates the employee more than 0.5 points higher than the employee's self-rating. Mentorship or exposure-based training is usually recommended.
              </li>
            </ul>
          </section>

          <section>
            <h3 className="font-semibold text-gray-900 mb-1">Severity and risk level</h3>
            <p>
              Severity is calculated as:{' '}
              <code className="bg-gray-100 px-1.5 py-0.5 rounded text-xs">(Performance Gap × 2) + Self-Assessment Gap + Confidence Gap</code>.{' '}
              Higher severity means the issue is more urgent.
            </p>
            <p className="mt-2">
              The overall risk level summarises total severity across all sections:
            </p>
            <ul className="list-disc ml-5 space-y-1 mt-1">
              <li><strong>High</strong> — total severity greater than 6, or more than 2 critical performance gaps.</li>
              <li><strong>Medium</strong> — total severity greater than 3, or more than 1 critical performance gap.</li>
              <li><strong>Low</strong> — at least one gap exists but total severity is 3 or less.</li>
              <li><strong>Minimal</strong> — no significant gaps detected; employee and manager views are aligned.</li>
            </ul>
          </section>

          <section>
            <h3 className="font-semibold text-gray-900 mb-1">Link to training needs</h3>
            <p>
              Any section flagged in the gap analysis is passed to the <strong>Training Needs & Recommendations</strong> card, where rule-based or AI-powered suggestions can be turned into internal training requests or external course referrals.
            </p>
          </section>

          <div className="text-xs text-gray-500 pt-2 border-t">
            Generated by the Zeenab Foods HR Performance Appraisal System.
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
