// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vedgkzikqccykuozkmxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlZGdremlrcWNjeWt1b3prbXhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMjIzOTcsImV4cCI6MjA2NTg5ODM5N30.uN1oTpq_8dGCl9hA_Mq9LOXhvcH2R0EJRhc9sTmp0-Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);